# CUDA_VISIBLE_DEVICES=0 python run.py --arch roberta_base --task RTE --restore-file /home/yujin-wa20/projects/DATE-2024-linear-softmax/I-BERT/outputs/none/RTE-base/wd0.1_ad0.1_d0.1_lr2e-5/1118-022020_ckpt/checkpoint_best.pt --lr 1e-6 --output-dir outputs-quant-fp8 --use-fp8-operator 1 --force-dequant gelu+layernorm # fast
# CUDA_VISIBLE_DEVICES=1 python run.py --arch roberta_base --task QQP --restore-file /home/yujin-wa20/projects/DATE-2024-linear-softmax/I-BERT/outputs/none/QQP-base/wd0.1_ad0.1_d0.1_lr1e-5/1117-150525_ckpt/checkpoint_best.pt --lr 1e-6 --output-dir outputs-quant-fp8 --use-fp8-operator 1 --force-dequant gelu+layernorm
# CUDA_VISIBLE_DEVICES=0 python run.py --arch roberta_base --task SST-2 --restore-file /home/yujin-wa20/projects/DATE-2024-linear-softmax/I-BERT/outputs/none/SST-2-base/wd0.1_ad0.1_d0.1_lr1e-5/1118-022834_ckpt/checkpoint_best.pt --lr 1e-6 --output-dir outputs-quant-fp8 --use-fp8-operator 1 --force-dequant gelu+layernorm
# CUDA_VISIBLE_DEVICES=1 python run.py --arch roberta_base --task STS-B --restore-file /home/yujin-wa20/projects/DATE-2024-linear-softmax/I-BERT/outputs/none/STS-B-base/wd0.1_ad0.1_d0.1_lr2e-5/1118-022041_ckpt/checkpoint_best.pt --lr 1e-6 --output-dir outputs-quant-fp8 --use-fp8-operator 1 --force-dequant gelu+layernorm # fast
# CUDA_VISIBLE_DEVICES=1 python run.py --arch roberta_base --task QNLI --restore-file /home/yujin-wa20/projects/DATE-2024-linear-softmax/I-BERT/outputs/none/QNLI-base/wd0.1_ad0.1_d0.1_lr1e-5/1117-151239_ckpt/checkpoint_best.pt --lr 1e-6 --output-dir outputs-quant-fp8 --use-fp8-operator 1 --force-dequant gelu+layernorm
# CUDA_VISIBLE_DEVICES=1 python run.py --arch roberta_base --task MRPC --restore-file /home/yujin-wa20/projects/DATE-2024-linear-softmax/I-BERT/outputs/none/MRPC-base/wd0.1_ad0.1_d0.1_lr1e-5/1117-150403_ckpt/checkpoint_best.pt --lr 1e-6 --output-dir outputs-quant-fp8 --use-fp8-operator 1 --force-dequant gelu+layernorm
CUDA_VISIBLE_DEVICES=1 python run.py --arch roberta_base --task MNLI --restore-file /home/yujin-wa20/projects/DATE-2024-linear-softmax/I-BERT/outputs/none/QNLI-base/wd0.1_ad0.1_d0.1_lr1e-5/1117-151239_ckpt/checkpoint_best.pt --lr 1e-6 --output-dir outputs-quant-fp8 --use-fp8-operator 1 --force-dequant gelu+layernorm
# CUDA_VISIBLE_DEVICES=1 python run.py --arch roberta_base --task CoLA --restore-file /home/yujin-wa20/projects/DATE-2024-linear-softmax/I-BERT/outputs/none/CoLA-base/wd0.1_ad0.1_d0.1_lr1e-5/1118-022820_ckpt/checkpoint_best.pt --lr 1e-6 --output-dir outputs-quant-fp8 --use-fp8-operator 1 --force-dequant gelu+layernorm

